######################################################################
# Automatically generated by qmake (3.0) ?? 11? 19 15:00:27 2017
######################################################################
QT+=widgets
TEMPLATE = app
TARGET = ShowPice
INCLUDEPATH += .
QT+=multimedia
# Input
HEADERS += showpice.h
FORMS += showpice.ui
SOURCES += main.cpp showpice.cpp
RESOURCES += img.qrc
